<!--
  Expandable API schema tree.

  Usage:
  Displays nested REST OpenAPI schemas and gRPC protobuf messages as an
  expandable object tree. The input tree is generated by the backend.
-->
<script setup lang="ts">
import { computed, ref } from 'vue'
import { ChevronRight } from 'lucide-vue-next'

import type { RuntimeSchemaNode } from '@/api/debug'

const props = defineProps<{
  nodes: RuntimeSchemaNode[]
}>()

interface VisibleNode {
  node: RuntimeSchemaNode
  key: string
  depth: number
}

const collapsed = ref<Set<string>>(new Set())

const visibleNodes = computed<VisibleNode[]>(() => {
  const rows: VisibleNode[] = []
  function visit(nodes: RuntimeSchemaNode[], depth: number, parentKey: string) {
    nodes.forEach((node, index) => {
      const key = `${parentKey}/${index}:${node.name}:${node.type}`
      rows.push({ node, key, depth })
      if (node.children?.length && !collapsed.value.has(key)) {
        visit(node.children, depth + 1, key)
      }
    })
  }
  visit(props.nodes, 0, 'root')
  return rows
})

function toggle(key: string, node: RuntimeSchemaNode) {
  if (!node.children?.length) return
  const next = new Set(collapsed.value)
  if (next.has(key)) {
    next.delete(key)
  } else {
    next.add(key)
  }
  collapsed.value = next
}

function formatValue(value: unknown): string {
  if (value === undefined || value === null || value === '') return '-'
  if (Array.isArray(value)) return value.length > 0 ? value.join(', ') : '-'
  if (typeof value === 'object') return JSON.stringify(value)
  return String(value)
}
</script>

<template>
  <div class="schema-tree">
    <div class="schema-row schema-head">
      <span>字段</span>
      <span>类型</span>
      <span>必填</span>
      <span>默认</span>
      <span>枚举</span>
      <span>说明</span>
    </div>
    <button
      v-for="item in visibleNodes"
      :key="item.key"
      class="schema-row schema-node"
      type="button"
      @click="toggle(item.key, item.node)"
    >
      <span class="schema-name" :style="{ '--schema-depth': item.depth }">
        <ChevronRight
          v-if="item.node.children?.length"
          class="schema-chevron"
          :class="{ collapsed: collapsed.has(item.key) }"
          :size="13"
        />
        <span v-else class="schema-spacer"></span>
        <code>{{ item.node.name }}</code>
      </span>
      <code>{{ item.node.type }}</code>
      <span>{{ item.node.required ? 'yes' : 'no' }}</span>
      <span>{{ formatValue(item.node.default) }}</span>
      <span>{{ formatValue(item.node.enum) }}</span>
      <span>{{ item.node.description || item.node.label || '-' }}</span>
    </button>
  </div>
</template>

<style scoped>
.schema-tree {
  display: grid;
  min-width: 0;
  border: 1px solid var(--color-border);
}

.schema-row {
  display: grid;
  grid-template-columns: minmax(220px, 1.5fr) minmax(180px, 1fr) 64px 88px minmax(120px, 0.8fr) minmax(180px, 1fr);
  gap: var(--space-8);
  align-items: center;
  min-height: 30px;
  padding: 0 var(--space-8);
  border: 0;
  border-bottom: 1px solid var(--color-border);
  background: transparent;
  color: var(--color-text-secondary);
  font-family: var(--font-ui);
  font-size: var(--font-size-xs);
  text-align: left;
}

.schema-row:last-child {
  border-bottom: 0;
}

.schema-head {
  color: var(--color-text-muted);
  background: var(--color-surface-raised);
}

.schema-node:hover {
  background: var(--color-bg-hover);
}

.schema-name {
  display: flex;
  align-items: center;
  min-width: 0;
  padding-left: calc(var(--schema-depth) * 18px);
}

.schema-chevron {
  flex: 0 0 auto;
  color: var(--color-text-muted);
  transition: transform var(--transition-fast);
  transform: rotate(90deg);
}

.schema-chevron.collapsed {
  transform: rotate(0deg);
}

.schema-spacer {
  width: 13px;
  flex: 0 0 auto;
}

code,
.schema-row span {
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

code {
  color: var(--color-text-primary);
  font-family: var(--font-text);
}
</style>
