# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent_service.api.grpc import agent_service_pb2 as agent__service__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agent_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """---------------------------------------------------------------------------
    AgentService — Agent 微服务 gRPC 接口定义

    覆盖能力:
    - AgentCore 的 4 个方法（流式 / 非流式 × 有状态 / 无状态）
    - SessionService 的 5 个 CRUD 方法
    ---------------------------------------------------------------------------

    ---- Agent 调用 ----
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamRun = channel.unary_stream(
                '/agent_service.AgentService/StreamRun',
                request_serializer=agent__service__pb2.RunRequest.SerializeToString,
                response_deserializer=agent__service__pb2.ChunkMessage.FromString,
                _registered_method=True)
        self.RunOnce = channel.unary_unary(
                '/agent_service.AgentService/RunOnce',
                request_serializer=agent__service__pb2.RunRequest.SerializeToString,
                response_deserializer=agent__service__pb2.RunResult.FromString,
                _registered_method=True)
        self.StreamSessionPrompt = channel.unary_stream(
                '/agent_service.AgentService/StreamSessionPrompt',
                request_serializer=agent__service__pb2.RunRequest.SerializeToString,
                response_deserializer=agent__service__pb2.ChunkMessage.FromString,
                _registered_method=True)
        self.RunSessionPrompt = channel.unary_unary(
                '/agent_service.AgentService/RunSessionPrompt',
                request_serializer=agent__service__pb2.RunRequest.SerializeToString,
                response_deserializer=agent__service__pb2.RunResult.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/agent_service.AgentService/CreateSession',
                request_serializer=agent__service__pb2.SessionCreateRequest.SerializeToString,
                response_deserializer=agent__service__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/agent_service.AgentService/GetSession',
                request_serializer=agent__service__pb2.SessionIdRequest.SerializeToString,
                response_deserializer=agent__service__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.ListUserSessions = channel.unary_unary(
                '/agent_service.AgentService/ListUserSessions',
                request_serializer=agent__service__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=agent__service__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.UpdateSessionName = channel.unary_unary(
                '/agent_service.AgentService/UpdateSessionName',
                request_serializer=agent__service__pb2.SessionUpdateRequest.SerializeToString,
                response_deserializer=agent__service__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/agent_service.AgentService/DeleteSession',
                request_serializer=agent__service__pb2.SessionIdRequest.SerializeToString,
                response_deserializer=agent__service__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.DeleteAllSessions = channel.unary_unary(
                '/agent_service.AgentService/DeleteAllSessions',
                request_serializer=agent__service__pb2.DeleteAllSessionsRequest.SerializeToString,
                response_deserializer=agent__service__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListMessages = channel.unary_unary(
                '/agent_service.AgentService/ListMessages',
                request_serializer=agent__service__pb2.ListMessagesRequest.SerializeToString,
                response_deserializer=agent__service__pb2.ListMessagesResponse.FromString,
                _registered_method=True)
        self.CancelSession = channel.unary_unary(
                '/agent_service.AgentService/CancelSession',
                request_serializer=agent__service__pb2.CancelRequest.SerializeToString,
                response_deserializer=agent__service__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.GetEvents = channel.unary_unary(
                '/agent_service.AgentService/GetEvents',
                request_serializer=agent__service__pb2.EventsRequest.SerializeToString,
                response_deserializer=agent__service__pb2.EventsResponse.FromString,
                _registered_method=True)
        self.GetRecallDetails = channel.unary_unary(
                '/agent_service.AgentService/GetRecallDetails',
                request_serializer=agent__service__pb2.RecallDetailsRequest.SerializeToString,
                response_deserializer=agent__service__pb2.RecallDetailsResponse.FromString,
                _registered_method=True)
        self.GetTaskSuggestions = channel.unary_unary(
                '/agent_service.AgentService/GetTaskSuggestions',
                request_serializer=agent__service__pb2.TaskSuggestionsRequest.SerializeToString,
                response_deserializer=agent__service__pb2.TaskSuggestionsResponse.FromString,
                _registered_method=True)
        self.GetTokenUsage = channel.unary_unary(
                '/agent_service.AgentService/GetTokenUsage',
                request_serializer=agent__service__pb2.TokenUsageRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                _registered_method=True)
        self.GetRegisteredTools = channel.unary_unary(
                '/agent_service.AgentService/GetRegisteredTools',
                request_serializer=agent__service__pb2.ToolListRequest.SerializeToString,
                response_deserializer=agent__service__pb2.ToolListResponse.FromString,
                _registered_method=True)
        self.EnsureUserProfile = channel.unary_unary(
                '/agent_service.AgentService/EnsureUserProfile',
                request_serializer=agent__service__pb2.UserProfileRequest.SerializeToString,
                response_deserializer=agent__service__pb2.UserProfileResponse.FromString,
                _registered_method=True)
        self.UpdateUserKnowledgeDir = channel.unary_unary(
                '/agent_service.AgentService/UpdateUserKnowledgeDir',
                request_serializer=agent__service__pb2.UserKnowledgeDirUpdateRequest.SerializeToString,
                response_deserializer=agent__service__pb2.UserProfileResponse.FromString,
                _registered_method=True)
        self.GetLLMConfig = channel.unary_unary(
                '/agent_service.AgentService/GetLLMConfig',
                request_serializer=agent__service__pb2.LLMConfigRequest.SerializeToString,
                response_deserializer=agent__service__pb2.LLMConfigResponse.FromString,
                _registered_method=True)
        self.SaveLLMConfig = channel.unary_unary(
                '/agent_service.AgentService/SaveLLMConfig',
                request_serializer=agent__service__pb2.LLMConfigSaveRequest.SerializeToString,
                response_deserializer=agent__service__pb2.LLMConfigResponse.FromString,
                _registered_method=True)
        self.ListLLMConfigPresets = channel.unary_unary(
                '/agent_service.AgentService/ListLLMConfigPresets',
                request_serializer=agent__service__pb2.LLMConfigRequest.SerializeToString,
                response_deserializer=agent__service__pb2.LLMConfigPresetListResponse.FromString,
                _registered_method=True)
        self.SaveLLMConfigPreset = channel.unary_unary(
                '/agent_service.AgentService/SaveLLMConfigPreset',
                request_serializer=agent__service__pb2.LLMConfigPresetSaveRequest.SerializeToString,
                response_deserializer=agent__service__pb2.LLMConfigPresetResponse.FromString,
                _registered_method=True)
        self.DeleteLLMConfigPreset = channel.unary_unary(
                '/agent_service.AgentService/DeleteLLMConfigPreset',
                request_serializer=agent__service__pb2.LLMConfigPresetDeleteRequest.SerializeToString,
                response_deserializer=agent__service__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.RebuildKnowledge = channel.unary_unary(
                '/agent_service.AgentService/RebuildKnowledge',
                request_serializer=agent__service__pb2.KnowledgeRebuildRequest.SerializeToString,
                response_deserializer=agent__service__pb2.KnowledgeRebuildResponse.FromString,
                _registered_method=True)
        self.UploadKnowledgeFile = channel.unary_unary(
                '/agent_service.AgentService/UploadKnowledgeFile',
                request_serializer=agent__service__pb2.KnowledgeFileUploadRequest.SerializeToString,
                response_deserializer=agent__service__pb2.KnowledgeRebuildResponse.FromString,
                _registered_method=True)
        self.ListKnowledgeFiles = channel.unary_unary(
                '/agent_service.AgentService/ListKnowledgeFiles',
                request_serializer=agent__service__pb2.KnowledgeFileTreeRequest.SerializeToString,
                response_deserializer=agent__service__pb2.KnowledgeFileTreeResponse.FromString,
                _registered_method=True)
        self.ReadKnowledgeFile = channel.unary_unary(
                '/agent_service.AgentService/ReadKnowledgeFile',
                request_serializer=agent__service__pb2.KnowledgeFileContentRequest.SerializeToString,
                response_deserializer=agent__service__pb2.KnowledgeFileContentResponse.FromString,
                _registered_method=True)
        self.WriteKnowledgeFile = channel.unary_unary(
                '/agent_service.AgentService/WriteKnowledgeFile',
                request_serializer=agent__service__pb2.KnowledgeFileWriteRequest.SerializeToString,
                response_deserializer=agent__service__pb2.KnowledgeFileNode.FromString,
                _registered_method=True)
        self.CreateKnowledgeFile = channel.unary_unary(
                '/agent_service.AgentService/CreateKnowledgeFile',
                request_serializer=agent__service__pb2.KnowledgeFileCreateRequest.SerializeToString,
                response_deserializer=agent__service__pb2.KnowledgeFileNode.FromString,
                _registered_method=True)
        self.CreateKnowledgeFolder = channel.unary_unary(
                '/agent_service.AgentService/CreateKnowledgeFolder',
                request_serializer=agent__service__pb2.KnowledgeFolderCreateRequest.SerializeToString,
                response_deserializer=agent__service__pb2.KnowledgeFileNode.FromString,
                _registered_method=True)
        self.CopyKnowledgePath = channel.unary_unary(
                '/agent_service.AgentService/CopyKnowledgePath',
                request_serializer=agent__service__pb2.KnowledgePathCopyRequest.SerializeToString,
                response_deserializer=agent__service__pb2.KnowledgeFileNode.FromString,
                _registered_method=True)
        self.DeleteKnowledgePath = channel.unary_unary(
                '/agent_service.AgentService/DeleteKnowledgePath',
                request_serializer=agent__service__pb2.KnowledgePathDeleteRequest.SerializeToString,
                response_deserializer=agent__service__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.RenameKnowledgePath = channel.unary_unary(
                '/agent_service.AgentService/RenameKnowledgePath',
                request_serializer=agent__service__pb2.KnowledgePathRenameRequest.SerializeToString,
                response_deserializer=agent__service__pb2.KnowledgeFileNode.FromString,
                _registered_method=True)
        self.ListSystemPromptEntries = channel.unary_unary(
                '/agent_service.AgentService/ListSystemPromptEntries',
                request_serializer=agent__service__pb2.SystemPromptRequest.SerializeToString,
                response_deserializer=agent__service__pb2.SystemPromptEntriesResponse.FromString,
                _registered_method=True)
        self.AddSystemPromptEntry = channel.unary_unary(
                '/agent_service.AgentService/AddSystemPromptEntry',
                request_serializer=agent__service__pb2.SystemPromptAddRequest.SerializeToString,
                response_deserializer=agent__service__pb2.SystemPromptEntryResponse.FromString,
                _registered_method=True)
        self.DeleteSystemPromptEntry = channel.unary_unary(
                '/agent_service.AgentService/DeleteSystemPromptEntry',
                request_serializer=agent__service__pb2.SystemPromptDeleteRequest.SerializeToString,
                response_deserializer=agent__service__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListCustomMemories = channel.unary_unary(
                '/agent_service.AgentService/ListCustomMemories',
                request_serializer=agent__service__pb2.MemoryListRequest.SerializeToString,
                response_deserializer=agent__service__pb2.MemoryListResponse.FromString,
                _registered_method=True)
        self.AddCustomMemory = channel.unary_unary(
                '/agent_service.AgentService/AddCustomMemory',
                request_serializer=agent__service__pb2.MemoryAddRequest.SerializeToString,
                response_deserializer=agent__service__pb2.MemoryEntryResponse.FromString,
                _registered_method=True)
        self.DeleteCustomMemory = channel.unary_unary(
                '/agent_service.AgentService/DeleteCustomMemory',
                request_serializer=agent__service__pb2.MemoryDeleteRequest.SerializeToString,
                response_deserializer=agent__service__pb2.DeleteResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """---------------------------------------------------------------------------
    AgentService — Agent 微服务 gRPC 接口定义

    覆盖能力:
    - AgentCore 的 4 个方法（流式 / 非流式 × 有状态 / 无状态）
    - SessionService 的 5 个 CRUD 方法
    ---------------------------------------------------------------------------

    ---- Agent 调用 ----
    """

    def StreamRun(self, request, context):
        """无状态流式运行（无长期记忆 / 知识库召回）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunOnce(self, request, context):
        """无状态单次运行，返回结构化结果。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSessionPrompt(self, request, context):
        """带 session 上下文的流式运行（长期记忆召回 + 消息持久化 + 逐节点推送）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSessionPrompt(self, request, context):
        """带 session 上下文的单次运行，缓冲全部节点后返回结构化结果。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """---- Session 管理 ----

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSessionName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAllSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessages(self, request, context):
        """---- 消息历史 ----

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelSession(self, request, context):
        """---- 取消执行 ----

        取消指定 session 正在执行的图,中断后部分输出自动保存。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvents(self, request, context):
        """---- 观测 / trace 事件 ----

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecallDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskSuggestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTokenUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegisteredTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnsureUserProfile(self, request, context):
        """---- 用户设置 ----

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserKnowledgeDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLLMConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveLLMConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLLMConfigPresets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveLLMConfigPreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLLMConfigPreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RebuildKnowledge(self, request, context):
        """知识库重建与上传
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadKnowledgeFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListKnowledgeFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadKnowledgeFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteKnowledgeFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateKnowledgeFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateKnowledgeFolder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyKnowledgePath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKnowledgePath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameKnowledgePath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSystemPromptEntries(self, request, context):
        """系统提示词条目
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSystemPromptEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSystemPromptEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCustomMemories(self, request, context):
        """自定义长期记忆
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCustomMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCustomMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamRun': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRun,
                    request_deserializer=agent__service__pb2.RunRequest.FromString,
                    response_serializer=agent__service__pb2.ChunkMessage.SerializeToString,
            ),
            'RunOnce': grpc.unary_unary_rpc_method_handler(
                    servicer.RunOnce,
                    request_deserializer=agent__service__pb2.RunRequest.FromString,
                    response_serializer=agent__service__pb2.RunResult.SerializeToString,
            ),
            'StreamSessionPrompt': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSessionPrompt,
                    request_deserializer=agent__service__pb2.RunRequest.FromString,
                    response_serializer=agent__service__pb2.ChunkMessage.SerializeToString,
            ),
            'RunSessionPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSessionPrompt,
                    request_deserializer=agent__service__pb2.RunRequest.FromString,
                    response_serializer=agent__service__pb2.RunResult.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=agent__service__pb2.SessionCreateRequest.FromString,
                    response_serializer=agent__service__pb2.SessionResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=agent__service__pb2.SessionIdRequest.FromString,
                    response_serializer=agent__service__pb2.SessionResponse.SerializeToString,
            ),
            'ListUserSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserSessions,
                    request_deserializer=agent__service__pb2.ListSessionsRequest.FromString,
                    response_serializer=agent__service__pb2.ListSessionsResponse.SerializeToString,
            ),
            'UpdateSessionName': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSessionName,
                    request_deserializer=agent__service__pb2.SessionUpdateRequest.FromString,
                    response_serializer=agent__service__pb2.SessionResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=agent__service__pb2.SessionIdRequest.FromString,
                    response_serializer=agent__service__pb2.DeleteResponse.SerializeToString,
            ),
            'DeleteAllSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAllSessions,
                    request_deserializer=agent__service__pb2.DeleteAllSessionsRequest.FromString,
                    response_serializer=agent__service__pb2.DeleteResponse.SerializeToString,
            ),
            'ListMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMessages,
                    request_deserializer=agent__service__pb2.ListMessagesRequest.FromString,
                    response_serializer=agent__service__pb2.ListMessagesResponse.SerializeToString,
            ),
            'CancelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelSession,
                    request_deserializer=agent__service__pb2.CancelRequest.FromString,
                    response_serializer=agent__service__pb2.CancelResponse.SerializeToString,
            ),
            'GetEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvents,
                    request_deserializer=agent__service__pb2.EventsRequest.FromString,
                    response_serializer=agent__service__pb2.EventsResponse.SerializeToString,
            ),
            'GetRecallDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecallDetails,
                    request_deserializer=agent__service__pb2.RecallDetailsRequest.FromString,
                    response_serializer=agent__service__pb2.RecallDetailsResponse.SerializeToString,
            ),
            'GetTaskSuggestions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskSuggestions,
                    request_deserializer=agent__service__pb2.TaskSuggestionsRequest.FromString,
                    response_serializer=agent__service__pb2.TaskSuggestionsResponse.SerializeToString,
            ),
            'GetTokenUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTokenUsage,
                    request_deserializer=agent__service__pb2.TokenUsageRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'GetRegisteredTools': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegisteredTools,
                    request_deserializer=agent__service__pb2.ToolListRequest.FromString,
                    response_serializer=agent__service__pb2.ToolListResponse.SerializeToString,
            ),
            'EnsureUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureUserProfile,
                    request_deserializer=agent__service__pb2.UserProfileRequest.FromString,
                    response_serializer=agent__service__pb2.UserProfileResponse.SerializeToString,
            ),
            'UpdateUserKnowledgeDir': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserKnowledgeDir,
                    request_deserializer=agent__service__pb2.UserKnowledgeDirUpdateRequest.FromString,
                    response_serializer=agent__service__pb2.UserProfileResponse.SerializeToString,
            ),
            'GetLLMConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLLMConfig,
                    request_deserializer=agent__service__pb2.LLMConfigRequest.FromString,
                    response_serializer=agent__service__pb2.LLMConfigResponse.SerializeToString,
            ),
            'SaveLLMConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveLLMConfig,
                    request_deserializer=agent__service__pb2.LLMConfigSaveRequest.FromString,
                    response_serializer=agent__service__pb2.LLMConfigResponse.SerializeToString,
            ),
            'ListLLMConfigPresets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLLMConfigPresets,
                    request_deserializer=agent__service__pb2.LLMConfigRequest.FromString,
                    response_serializer=agent__service__pb2.LLMConfigPresetListResponse.SerializeToString,
            ),
            'SaveLLMConfigPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveLLMConfigPreset,
                    request_deserializer=agent__service__pb2.LLMConfigPresetSaveRequest.FromString,
                    response_serializer=agent__service__pb2.LLMConfigPresetResponse.SerializeToString,
            ),
            'DeleteLLMConfigPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLLMConfigPreset,
                    request_deserializer=agent__service__pb2.LLMConfigPresetDeleteRequest.FromString,
                    response_serializer=agent__service__pb2.DeleteResponse.SerializeToString,
            ),
            'RebuildKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.RebuildKnowledge,
                    request_deserializer=agent__service__pb2.KnowledgeRebuildRequest.FromString,
                    response_serializer=agent__service__pb2.KnowledgeRebuildResponse.SerializeToString,
            ),
            'UploadKnowledgeFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadKnowledgeFile,
                    request_deserializer=agent__service__pb2.KnowledgeFileUploadRequest.FromString,
                    response_serializer=agent__service__pb2.KnowledgeRebuildResponse.SerializeToString,
            ),
            'ListKnowledgeFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListKnowledgeFiles,
                    request_deserializer=agent__service__pb2.KnowledgeFileTreeRequest.FromString,
                    response_serializer=agent__service__pb2.KnowledgeFileTreeResponse.SerializeToString,
            ),
            'ReadKnowledgeFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadKnowledgeFile,
                    request_deserializer=agent__service__pb2.KnowledgeFileContentRequest.FromString,
                    response_serializer=agent__service__pb2.KnowledgeFileContentResponse.SerializeToString,
            ),
            'WriteKnowledgeFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteKnowledgeFile,
                    request_deserializer=agent__service__pb2.KnowledgeFileWriteRequest.FromString,
                    response_serializer=agent__service__pb2.KnowledgeFileNode.SerializeToString,
            ),
            'CreateKnowledgeFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateKnowledgeFile,
                    request_deserializer=agent__service__pb2.KnowledgeFileCreateRequest.FromString,
                    response_serializer=agent__service__pb2.KnowledgeFileNode.SerializeToString,
            ),
            'CreateKnowledgeFolder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateKnowledgeFolder,
                    request_deserializer=agent__service__pb2.KnowledgeFolderCreateRequest.FromString,
                    response_serializer=agent__service__pb2.KnowledgeFileNode.SerializeToString,
            ),
            'CopyKnowledgePath': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyKnowledgePath,
                    request_deserializer=agent__service__pb2.KnowledgePathCopyRequest.FromString,
                    response_serializer=agent__service__pb2.KnowledgeFileNode.SerializeToString,
            ),
            'DeleteKnowledgePath': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKnowledgePath,
                    request_deserializer=agent__service__pb2.KnowledgePathDeleteRequest.FromString,
                    response_serializer=agent__service__pb2.DeleteResponse.SerializeToString,
            ),
            'RenameKnowledgePath': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameKnowledgePath,
                    request_deserializer=agent__service__pb2.KnowledgePathRenameRequest.FromString,
                    response_serializer=agent__service__pb2.KnowledgeFileNode.SerializeToString,
            ),
            'ListSystemPromptEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSystemPromptEntries,
                    request_deserializer=agent__service__pb2.SystemPromptRequest.FromString,
                    response_serializer=agent__service__pb2.SystemPromptEntriesResponse.SerializeToString,
            ),
            'AddSystemPromptEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSystemPromptEntry,
                    request_deserializer=agent__service__pb2.SystemPromptAddRequest.FromString,
                    response_serializer=agent__service__pb2.SystemPromptEntryResponse.SerializeToString,
            ),
            'DeleteSystemPromptEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSystemPromptEntry,
                    request_deserializer=agent__service__pb2.SystemPromptDeleteRequest.FromString,
                    response_serializer=agent__service__pb2.DeleteResponse.SerializeToString,
            ),
            'ListCustomMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCustomMemories,
                    request_deserializer=agent__service__pb2.MemoryListRequest.FromString,
                    response_serializer=agent__service__pb2.MemoryListResponse.SerializeToString,
            ),
            'AddCustomMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCustomMemory,
                    request_deserializer=agent__service__pb2.MemoryAddRequest.FromString,
                    response_serializer=agent__service__pb2.MemoryEntryResponse.SerializeToString,
            ),
            'DeleteCustomMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCustomMemory,
                    request_deserializer=agent__service__pb2.MemoryDeleteRequest.FromString,
                    response_serializer=agent__service__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent_service.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent_service.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """---------------------------------------------------------------------------
    AgentService — Agent 微服务 gRPC 接口定义

    覆盖能力:
    - AgentCore 的 4 个方法（流式 / 非流式 × 有状态 / 无状态）
    - SessionService 的 5 个 CRUD 方法
    ---------------------------------------------------------------------------

    ---- Agent 调用 ----
    """

    @staticmethod
    def StreamRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent_service.AgentService/StreamRun',
            agent__service__pb2.RunRequest.SerializeToString,
            agent__service__pb2.ChunkMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunOnce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/RunOnce',
            agent__service__pb2.RunRequest.SerializeToString,
            agent__service__pb2.RunResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSessionPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent_service.AgentService/StreamSessionPrompt',
            agent__service__pb2.RunRequest.SerializeToString,
            agent__service__pb2.ChunkMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunSessionPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/RunSessionPrompt',
            agent__service__pb2.RunRequest.SerializeToString,
            agent__service__pb2.RunResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/CreateSession',
            agent__service__pb2.SessionCreateRequest.SerializeToString,
            agent__service__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/GetSession',
            agent__service__pb2.SessionIdRequest.SerializeToString,
            agent__service__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/ListUserSessions',
            agent__service__pb2.ListSessionsRequest.SerializeToString,
            agent__service__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSessionName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/UpdateSessionName',
            agent__service__pb2.SessionUpdateRequest.SerializeToString,
            agent__service__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/DeleteSession',
            agent__service__pb2.SessionIdRequest.SerializeToString,
            agent__service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAllSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/DeleteAllSessions',
            agent__service__pb2.DeleteAllSessionsRequest.SerializeToString,
            agent__service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/ListMessages',
            agent__service__pb2.ListMessagesRequest.SerializeToString,
            agent__service__pb2.ListMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/CancelSession',
            agent__service__pb2.CancelRequest.SerializeToString,
            agent__service__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/GetEvents',
            agent__service__pb2.EventsRequest.SerializeToString,
            agent__service__pb2.EventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecallDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/GetRecallDetails',
            agent__service__pb2.RecallDetailsRequest.SerializeToString,
            agent__service__pb2.RecallDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskSuggestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/GetTaskSuggestions',
            agent__service__pb2.TaskSuggestionsRequest.SerializeToString,
            agent__service__pb2.TaskSuggestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTokenUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/GetTokenUsage',
            agent__service__pb2.TokenUsageRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRegisteredTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/GetRegisteredTools',
            agent__service__pb2.ToolListRequest.SerializeToString,
            agent__service__pb2.ToolListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnsureUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/EnsureUserProfile',
            agent__service__pb2.UserProfileRequest.SerializeToString,
            agent__service__pb2.UserProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserKnowledgeDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/UpdateUserKnowledgeDir',
            agent__service__pb2.UserKnowledgeDirUpdateRequest.SerializeToString,
            agent__service__pb2.UserProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLLMConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/GetLLMConfig',
            agent__service__pb2.LLMConfigRequest.SerializeToString,
            agent__service__pb2.LLMConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveLLMConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/SaveLLMConfig',
            agent__service__pb2.LLMConfigSaveRequest.SerializeToString,
            agent__service__pb2.LLMConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLLMConfigPresets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/ListLLMConfigPresets',
            agent__service__pb2.LLMConfigRequest.SerializeToString,
            agent__service__pb2.LLMConfigPresetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveLLMConfigPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/SaveLLMConfigPreset',
            agent__service__pb2.LLMConfigPresetSaveRequest.SerializeToString,
            agent__service__pb2.LLMConfigPresetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteLLMConfigPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/DeleteLLMConfigPreset',
            agent__service__pb2.LLMConfigPresetDeleteRequest.SerializeToString,
            agent__service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RebuildKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/RebuildKnowledge',
            agent__service__pb2.KnowledgeRebuildRequest.SerializeToString,
            agent__service__pb2.KnowledgeRebuildResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadKnowledgeFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/UploadKnowledgeFile',
            agent__service__pb2.KnowledgeFileUploadRequest.SerializeToString,
            agent__service__pb2.KnowledgeRebuildResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListKnowledgeFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/ListKnowledgeFiles',
            agent__service__pb2.KnowledgeFileTreeRequest.SerializeToString,
            agent__service__pb2.KnowledgeFileTreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadKnowledgeFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/ReadKnowledgeFile',
            agent__service__pb2.KnowledgeFileContentRequest.SerializeToString,
            agent__service__pb2.KnowledgeFileContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteKnowledgeFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/WriteKnowledgeFile',
            agent__service__pb2.KnowledgeFileWriteRequest.SerializeToString,
            agent__service__pb2.KnowledgeFileNode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateKnowledgeFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/CreateKnowledgeFile',
            agent__service__pb2.KnowledgeFileCreateRequest.SerializeToString,
            agent__service__pb2.KnowledgeFileNode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateKnowledgeFolder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/CreateKnowledgeFolder',
            agent__service__pb2.KnowledgeFolderCreateRequest.SerializeToString,
            agent__service__pb2.KnowledgeFileNode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CopyKnowledgePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/CopyKnowledgePath',
            agent__service__pb2.KnowledgePathCopyRequest.SerializeToString,
            agent__service__pb2.KnowledgeFileNode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKnowledgePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/DeleteKnowledgePath',
            agent__service__pb2.KnowledgePathDeleteRequest.SerializeToString,
            agent__service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameKnowledgePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/RenameKnowledgePath',
            agent__service__pb2.KnowledgePathRenameRequest.SerializeToString,
            agent__service__pb2.KnowledgeFileNode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSystemPromptEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/ListSystemPromptEntries',
            agent__service__pb2.SystemPromptRequest.SerializeToString,
            agent__service__pb2.SystemPromptEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSystemPromptEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/AddSystemPromptEntry',
            agent__service__pb2.SystemPromptAddRequest.SerializeToString,
            agent__service__pb2.SystemPromptEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSystemPromptEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/DeleteSystemPromptEntry',
            agent__service__pb2.SystemPromptDeleteRequest.SerializeToString,
            agent__service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCustomMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/ListCustomMemories',
            agent__service__pb2.MemoryListRequest.SerializeToString,
            agent__service__pb2.MemoryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCustomMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/AddCustomMemory',
            agent__service__pb2.MemoryAddRequest.SerializeToString,
            agent__service__pb2.MemoryEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCustomMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/DeleteCustomMemory',
            agent__service__pb2.MemoryDeleteRequest.SerializeToString,
            agent__service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
