# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent_service.api.grpc import agent_service_pb2 as agent__service__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agent_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """---------------------------------------------------------------------------
    AgentService — Agent 微服务 gRPC 接口定义

    覆盖能力:
    - AgentCore 的 4 个方法（流式 / 非流式 × 有状态 / 无状态）
    - SessionService 的 5 个 CRUD 方法
    ---------------------------------------------------------------------------

    ---- Agent 调用 ----
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamRun = channel.unary_stream(
                '/agent_service.AgentService/StreamRun',
                request_serializer=agent__service__pb2.RunRequest.SerializeToString,
                response_deserializer=agent__service__pb2.ChunkMessage.FromString,
                _registered_method=True)
        self.RunOnce = channel.unary_unary(
                '/agent_service.AgentService/RunOnce',
                request_serializer=agent__service__pb2.RunRequest.SerializeToString,
                response_deserializer=agent__service__pb2.RunResult.FromString,
                _registered_method=True)
        self.StreamSessionPrompt = channel.unary_stream(
                '/agent_service.AgentService/StreamSessionPrompt',
                request_serializer=agent__service__pb2.RunRequest.SerializeToString,
                response_deserializer=agent__service__pb2.ChunkMessage.FromString,
                _registered_method=True)
        self.RunSessionPrompt = channel.unary_unary(
                '/agent_service.AgentService/RunSessionPrompt',
                request_serializer=agent__service__pb2.RunRequest.SerializeToString,
                response_deserializer=agent__service__pb2.RunResult.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/agent_service.AgentService/CreateSession',
                request_serializer=agent__service__pb2.SessionCreateRequest.SerializeToString,
                response_deserializer=agent__service__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/agent_service.AgentService/GetSession',
                request_serializer=agent__service__pb2.SessionIdRequest.SerializeToString,
                response_deserializer=agent__service__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.ListUserSessions = channel.unary_unary(
                '/agent_service.AgentService/ListUserSessions',
                request_serializer=agent__service__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=agent__service__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.UpdateSessionName = channel.unary_unary(
                '/agent_service.AgentService/UpdateSessionName',
                request_serializer=agent__service__pb2.SessionUpdateRequest.SerializeToString,
                response_deserializer=agent__service__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/agent_service.AgentService/DeleteSession',
                request_serializer=agent__service__pb2.SessionIdRequest.SerializeToString,
                response_deserializer=agent__service__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.DeleteAllSessions = channel.unary_unary(
                '/agent_service.AgentService/DeleteAllSessions',
                request_serializer=agent__service__pb2.DeleteAllSessionsRequest.SerializeToString,
                response_deserializer=agent__service__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListMessages = channel.unary_unary(
                '/agent_service.AgentService/ListMessages',
                request_serializer=agent__service__pb2.ListMessagesRequest.SerializeToString,
                response_deserializer=agent__service__pb2.ListMessagesResponse.FromString,
                _registered_method=True)
        self.CancelSession = channel.unary_unary(
                '/agent_service.AgentService/CancelSession',
                request_serializer=agent__service__pb2.CancelRequest.SerializeToString,
                response_deserializer=agent__service__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.GetEvents = channel.unary_unary(
                '/agent_service.AgentService/GetEvents',
                request_serializer=agent__service__pb2.EventsRequest.SerializeToString,
                response_deserializer=agent__service__pb2.EventsResponse.FromString,
                _registered_method=True)
        self.GetRecallDetails = channel.unary_unary(
                '/agent_service.AgentService/GetRecallDetails',
                request_serializer=agent__service__pb2.RecallDetailsRequest.SerializeToString,
                response_deserializer=agent__service__pb2.RecallDetailsResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """---------------------------------------------------------------------------
    AgentService — Agent 微服务 gRPC 接口定义

    覆盖能力:
    - AgentCore 的 4 个方法（流式 / 非流式 × 有状态 / 无状态）
    - SessionService 的 5 个 CRUD 方法
    ---------------------------------------------------------------------------

    ---- Agent 调用 ----
    """

    def StreamRun(self, request, context):
        """无状态流式运行（无长期记忆 / 知识库召回）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunOnce(self, request, context):
        """无状态单次运行，返回结构化结果。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSessionPrompt(self, request, context):
        """带 session 上下文的流式运行（长期记忆召回 + 消息持久化 + 逐节点推送）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSessionPrompt(self, request, context):
        """带 session 上下文的单次运行，缓冲全部节点后返回结构化结果。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """---- Session 管理 ----

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSessionName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAllSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessages(self, request, context):
        """---- 消息历史 ----

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelSession(self, request, context):
        """---- 取消执行 ----

        取消指定 session 正在执行的图,中断后部分输出自动保存。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvents(self, request, context):
        """---- 观测 / trace 事件 ----

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecallDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamRun': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRun,
                    request_deserializer=agent__service__pb2.RunRequest.FromString,
                    response_serializer=agent__service__pb2.ChunkMessage.SerializeToString,
            ),
            'RunOnce': grpc.unary_unary_rpc_method_handler(
                    servicer.RunOnce,
                    request_deserializer=agent__service__pb2.RunRequest.FromString,
                    response_serializer=agent__service__pb2.RunResult.SerializeToString,
            ),
            'StreamSessionPrompt': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSessionPrompt,
                    request_deserializer=agent__service__pb2.RunRequest.FromString,
                    response_serializer=agent__service__pb2.ChunkMessage.SerializeToString,
            ),
            'RunSessionPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSessionPrompt,
                    request_deserializer=agent__service__pb2.RunRequest.FromString,
                    response_serializer=agent__service__pb2.RunResult.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=agent__service__pb2.SessionCreateRequest.FromString,
                    response_serializer=agent__service__pb2.SessionResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=agent__service__pb2.SessionIdRequest.FromString,
                    response_serializer=agent__service__pb2.SessionResponse.SerializeToString,
            ),
            'ListUserSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserSessions,
                    request_deserializer=agent__service__pb2.ListSessionsRequest.FromString,
                    response_serializer=agent__service__pb2.ListSessionsResponse.SerializeToString,
            ),
            'UpdateSessionName': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSessionName,
                    request_deserializer=agent__service__pb2.SessionUpdateRequest.FromString,
                    response_serializer=agent__service__pb2.SessionResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=agent__service__pb2.SessionIdRequest.FromString,
                    response_serializer=agent__service__pb2.DeleteResponse.SerializeToString,
            ),
            'DeleteAllSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAllSessions,
                    request_deserializer=agent__service__pb2.DeleteAllSessionsRequest.FromString,
                    response_serializer=agent__service__pb2.DeleteResponse.SerializeToString,
            ),
            'ListMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMessages,
                    request_deserializer=agent__service__pb2.ListMessagesRequest.FromString,
                    response_serializer=agent__service__pb2.ListMessagesResponse.SerializeToString,
            ),
            'CancelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelSession,
                    request_deserializer=agent__service__pb2.CancelRequest.FromString,
                    response_serializer=agent__service__pb2.CancelResponse.SerializeToString,
            ),
            'GetEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvents,
                    request_deserializer=agent__service__pb2.EventsRequest.FromString,
                    response_serializer=agent__service__pb2.EventsResponse.SerializeToString,
            ),
            'GetRecallDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecallDetails,
                    request_deserializer=agent__service__pb2.RecallDetailsRequest.FromString,
                    response_serializer=agent__service__pb2.RecallDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent_service.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent_service.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """---------------------------------------------------------------------------
    AgentService — Agent 微服务 gRPC 接口定义

    覆盖能力:
    - AgentCore 的 4 个方法（流式 / 非流式 × 有状态 / 无状态）
    - SessionService 的 5 个 CRUD 方法
    ---------------------------------------------------------------------------

    ---- Agent 调用 ----
    """

    @staticmethod
    def StreamRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent_service.AgentService/StreamRun',
            agent__service__pb2.RunRequest.SerializeToString,
            agent__service__pb2.ChunkMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunOnce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/RunOnce',
            agent__service__pb2.RunRequest.SerializeToString,
            agent__service__pb2.RunResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSessionPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent_service.AgentService/StreamSessionPrompt',
            agent__service__pb2.RunRequest.SerializeToString,
            agent__service__pb2.ChunkMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunSessionPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/RunSessionPrompt',
            agent__service__pb2.RunRequest.SerializeToString,
            agent__service__pb2.RunResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/CreateSession',
            agent__service__pb2.SessionCreateRequest.SerializeToString,
            agent__service__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/GetSession',
            agent__service__pb2.SessionIdRequest.SerializeToString,
            agent__service__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/ListUserSessions',
            agent__service__pb2.ListSessionsRequest.SerializeToString,
            agent__service__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSessionName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/UpdateSessionName',
            agent__service__pb2.SessionUpdateRequest.SerializeToString,
            agent__service__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/DeleteSession',
            agent__service__pb2.SessionIdRequest.SerializeToString,
            agent__service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAllSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/DeleteAllSessions',
            agent__service__pb2.DeleteAllSessionsRequest.SerializeToString,
            agent__service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/ListMessages',
            agent__service__pb2.ListMessagesRequest.SerializeToString,
            agent__service__pb2.ListMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/CancelSession',
            agent__service__pb2.CancelRequest.SerializeToString,
            agent__service__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/GetEvents',
            agent__service__pb2.EventsRequest.SerializeToString,
            agent__service__pb2.EventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecallDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_service.AgentService/GetRecallDetails',
            agent__service__pb2.RecallDetailsRequest.SerializeToString,
            agent__service__pb2.RecallDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
