/*
 * API route registry for the editor front-end.
 *
 * Usage:
 * Import these constants from API clients and stores instead of hard-coding
 * endpoint strings inside components.
 */

export const API_ROUTES = {
  SETTINGS_PROFILE: '/settings/profile',
  SETTINGS_KNOWLEDGE_DIR: '/settings/profile/knowledge-dir',
  SETTINGS_FONT_CONFIG: '/settings/appearance/font',
  SETTINGS_APPEARANCE_CONFIG: '/settings/appearance/config',
  SETTINGS_KNOWLEDGE_INGESTION: '/settings/profile/ingestion',
  SETTINGS_SYSTEM_PROMPT: '/settings/memory/system-prompts',
  SETTINGS_SYSTEM_PROMPT_ENTRIES: '/settings/memory/system-prompts',
  SETTINGS_MEMORIES: '/settings/memory/memories',
  KNOWLEDGE_REBUILD: '/knowledge/rebuild',
  KNOWLEDGE_REBUILD_STREAM: '/knowledge/rebuild/stream',
  KNOWLEDGE_FILES: '/knowledge/files',
  KNOWLEDGE_FILE_CREATE: '/knowledge/files/file',
  KNOWLEDGE_FILE_CONTENT: '/knowledge/files/content',
  KNOWLEDGE_FILE_PREVIEW: '/knowledge/files/preview',
  KNOWLEDGE_FILE_UPLOAD: '/knowledge/files/upload',
  KNOWLEDGE_FILE_INGEST: '/knowledge/files/ingest',
  KNOWLEDGE_FILE_INGEST_STREAM: '/knowledge/files/ingest/stream',
  KNOWLEDGE_FILE_INGEST_PATH: '/knowledge/files/ingest-path',
  KNOWLEDGE_FILE_INGEST_PATH_STREAM: '/knowledge/files/ingest-path/stream',
  KNOWLEDGE_FILE_FOLDER: '/knowledge/files/folder',
  KNOWLEDGE_FILE_COPY: '/knowledge/files/copy',
  KNOWLEDGE_FILE_RENAME: '/knowledge/files/rename',
  KNOWLEDGE_FILE_TRASH: '/knowledge/files/trash',
  KNOWLEDGE_FILE_EVENTS: '/knowledge/files/events',
  KNOWLEDGE_INDEX_RUN: '/knowledge/index/run',
  KNOWLEDGE_INDEX_STATUS: '/knowledge/index/status',
  AGENT_STREAM: '/agent/stream',
  AGENT_STREAM_RUN: '/agent/stream-run',
  AGENT_ATTACHMENTS_UPLOAD: '/agent/attachments/upload',
  AGENT_ATTACHMENTS: '/agent/attachments',
  AGENT_CURRENT_DOCUMENT_CONTEXT: '/agent/editor-context/current-document',
  AGENT_TOOLS: '/agent/tools',
  AGENT_EVENTS: '/agent/events',
  AGENT_RECALL_DETAILS: '/agent/recall-details',
  AGENT_TASK_SUGGESTIONS: '/agent/task-suggestions',
  AGENT_TOKEN_USAGE: '/agent/token-usage',
  DEBUG_RUNTIME_APIS: '/debug/runtime-apis',
  DEBUG_MULTIMODAL_INGESTION: '/debug/multimodal-ingestion',
  KNOWLEDGE_SEARCH: '/knowledge/search',
  KNOWLEDGE_GRAPH: '/knowledge/graph',
  KNOWLEDGE_GRAPH_REBUILD: '/knowledge/graph/rebuild',
  KNOWLEDGE_GRAPH_REBUILD_STATUS: '/knowledge/graph/rebuild/status',
  KNOWLEDGE_GRAPH_DEDUP: '/knowledge/graph/dedup',
  KNOWLEDGE_GRAPH_DEDUP_STATUS: '/knowledge/graph/dedup/status',
  SETTINGS_MODEL_CONFIG: '/settings/llm/config',
  SETTINGS_MODEL_CONFIG_SAVED: '/settings/llm/config/saved',
  SETTINGS_WEB_SEARCH: '/settings/web-search/config',
  SETTINGS_DISABLED_TOOLS: '/settings/tools/disabled',
  SETTINGS_AVAILABLE_TOOLS: '/settings/tools/available',
  SETTINGS_TERMINAL_SANDBOX: '/settings/terminal/sandbox',
  SETTINGS_GRAPH_CONFIG: '/settings/graph/config',
  SETTINGS_SAFETY_SENSITIVE_WORDS: '/settings/safety/sensitive-words',
  SETTINGS_MODEL_STATUS: '/settings/models/status',
  SETTINGS_MODEL_DOWNLOAD: '/settings/models/download',
  SETTINGS_MODEL_LOAD: '/settings/models/load',
  SETTINGS_MODEL_CHECK: '/settings/models/check',
  SETTINGS_MODEL_DOWNLOAD_PROGRESS: '/settings/models/download-progress',
  SETTINGS_STORAGE_CONFIG: '/settings/storage/config',
  SETTINGS_STORAGE_CLEAR: '/settings/storage/clear',
  TODO_LIST: '/todo/list',
  TODO_ADD: '/todo/add',
  TODO_TOGGLE: '/todo/toggle',
  TODO_EDIT: '/todo/edit',
  TODO_DELETE: '/todo/delete',
} as const
