"""baseline_schema

Revision ID: 20260829_0001
Revises: 
Create Date: 2026-08-29 04:33:02.648321
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '20260829_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this revision."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_events',
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('object_id', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_activity_events_action'), 'activity_events', ['action'], unique=False)
    op.create_index(op.f('ix_activity_events_created_at'), 'activity_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_events_module'), 'activity_events', ['module'], unique=False)
    op.create_index(op.f('ix_activity_events_object_id'), 'activity_events', ['object_id'], unique=False)
    op.create_index(op.f('ix_activity_events_source'), 'activity_events', ['source'], unique=False)
    op.create_index(op.f('ix_activity_events_user_id'), 'activity_events', ['user_id'], unique=False)
    op.create_table('agent_change_snapshots',
    sa.Column('snapshot_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('edits_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('is_undone', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_agent_change_snapshots_created_at'), 'agent_change_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_change_snapshots_is_finalized'), 'agent_change_snapshots', ['is_finalized'], unique=False)
    op.create_index(op.f('ix_agent_change_snapshots_is_undone'), 'agent_change_snapshots', ['is_undone'], unique=False)
    op.create_index(op.f('ix_agent_change_snapshots_run_id'), 'agent_change_snapshots', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_change_snapshots_session_id'), 'agent_change_snapshots', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_change_snapshots_user_id'), 'agent_change_snapshots', ['user_id'], unique=False)
    op.create_table('agent_queue_settings',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('agent_queue_tasks',
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('attachments_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('previous_task_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_agent_queue_tasks_created_at'), 'agent_queue_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_queue_tasks_previous_task_id'), 'agent_queue_tasks', ['previous_task_id'], unique=False)
    op.create_index(op.f('ix_agent_queue_tasks_priority'), 'agent_queue_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_agent_queue_tasks_session_id'), 'agent_queue_tasks', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_queue_tasks_status'), 'agent_queue_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_agent_queue_tasks_updated_at'), 'agent_queue_tasks', ['updated_at'], unique=False)
    op.create_index(op.f('ix_agent_queue_tasks_user_id'), 'agent_queue_tasks', ['user_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('session_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('state_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_agent_sessions_created_at'), 'agent_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_sessions_updated_at'), 'agent_sessions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_table('agent_token_usage',
    sa.Column('token_usage_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('node', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('model_tier', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token_usage_id')
    )
    op.create_index(op.f('ix_agent_token_usage_created_at'), 'agent_token_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_token_usage_message_id'), 'agent_token_usage', ['message_id'], unique=False)
    op.create_index(op.f('ix_agent_token_usage_model_name'), 'agent_token_usage', ['model_name'], unique=False)
    op.create_index(op.f('ix_agent_token_usage_model_tier'), 'agent_token_usage', ['model_tier'], unique=False)
    op.create_index(op.f('ix_agent_token_usage_node'), 'agent_token_usage', ['node'], unique=False)
    op.create_index(op.f('ix_agent_token_usage_session_id'), 'agent_token_usage', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_token_usage_total_tokens'), 'agent_token_usage', ['total_tokens'], unique=False)
    op.create_index(op.f('ix_agent_token_usage_user_id'), 'agent_token_usage', ['user_id'], unique=False)
    op.create_table('automation_runs',
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('automation_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('output', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_automation_runs_automation_id'), 'automation_runs', ['automation_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_user_id'), 'automation_runs', ['user_id'], unique=False)
    op.create_table('automation_tasks',
    sa.Column('automation_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('todo_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('recurrence_frequency', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('recurrence_interval', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('access_mode', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('lease_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('automation_id')
    )
    op.create_index(op.f('ix_automation_tasks_enabled'), 'automation_tasks', ['enabled'], unique=False)
    op.create_index(op.f('ix_automation_tasks_lease_id'), 'automation_tasks', ['lease_id'], unique=False)
    op.create_index(op.f('ix_automation_tasks_lease_until'), 'automation_tasks', ['lease_until'], unique=False)
    op.create_index(op.f('ix_automation_tasks_next_run_at'), 'automation_tasks', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_automation_tasks_todo_id'), 'automation_tasks', ['todo_id'], unique=True)
    op.create_index(op.f('ix_automation_tasks_user_id'), 'automation_tasks', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('favorite_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('library_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('favorite_id'),
    sa.UniqueConstraint('user_id', 'library_id', 'target_type', 'target_id', name='uq_favorites_target')
    )
    op.create_index(op.f('ix_favorites_created_at'), 'favorites', ['created_at'], unique=False)
    op.create_index(op.f('ix_favorites_library_id'), 'favorites', ['library_id'], unique=False)
    op.create_index(op.f('ix_favorites_target_id'), 'favorites', ['target_id'], unique=False)
    op.create_index(op.f('ix_favorites_target_type'), 'favorites', ['target_type'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('feedback_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('page', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('knowledge_graph_document_status',
    sa.Column('status_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('library_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('relation_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_index(op.f('ix_knowledge_graph_document_status_document_id'), 'knowledge_graph_document_status', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_document_status_library_id'), 'knowledge_graph_document_status', ['library_id'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_document_status_source_hash'), 'knowledge_graph_document_status', ['source_hash'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_document_status_status'), 'knowledge_graph_document_status', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_document_status_updated_at'), 'knowledge_graph_document_status', ['updated_at'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_document_status_user_id'), 'knowledge_graph_document_status', ['user_id'], unique=False)
    op.create_table('knowledge_graph_edges',
    sa.Column('edge_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('library_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('source_node_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('target_node_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('relation_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('source_document_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source_section_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_index(op.f('ix_knowledge_graph_edges_created_at'), 'knowledge_graph_edges', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_edges_library_id'), 'knowledge_graph_edges', ['library_id'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_edges_relation_type'), 'knowledge_graph_edges', ['relation_type'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_edges_source_document_id'), 'knowledge_graph_edges', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_edges_source_node_id'), 'knowledge_graph_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_edges_source_section_id'), 'knowledge_graph_edges', ['source_section_id'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_edges_target_node_id'), 'knowledge_graph_edges', ['target_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_edges_updated_at'), 'knowledge_graph_edges', ['updated_at'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_edges_user_id'), 'knowledge_graph_edges', ['user_id'], unique=False)
    op.create_table('knowledge_graph_nodes',
    sa.Column('node_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('library_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('node_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('normalized_label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source_uri', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('source_range_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_index(op.f('ix_knowledge_graph_nodes_created_at'), 'knowledge_graph_nodes', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_nodes_document_id'), 'knowledge_graph_nodes', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_nodes_entity_type'), 'knowledge_graph_nodes', ['entity_type'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_nodes_label'), 'knowledge_graph_nodes', ['label'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_nodes_library_id'), 'knowledge_graph_nodes', ['library_id'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_nodes_node_type'), 'knowledge_graph_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_nodes_normalized_label'), 'knowledge_graph_nodes', ['normalized_label'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_nodes_updated_at'), 'knowledge_graph_nodes', ['updated_at'], unique=False)
    op.create_index(op.f('ix_knowledge_graph_nodes_user_id'), 'knowledge_graph_nodes', ['user_id'], unique=False)
    op.create_table('knowledge_ingestion_jobs',
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('library_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pipeline', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('stage_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage_current', sa.Integer(), nullable=False),
    sa.Column('stage_total', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('mtime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('result_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_knowledge_ingestion_jobs_cancel_requested'), 'knowledge_ingestion_jobs', ['cancel_requested'], unique=False)
    op.create_index(op.f('ix_knowledge_ingestion_jobs_created_at'), 'knowledge_ingestion_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_ingestion_jobs_library_id'), 'knowledge_ingestion_jobs', ['library_id'], unique=False)
    op.create_index(op.f('ix_knowledge_ingestion_jobs_path'), 'knowledge_ingestion_jobs', ['path'], unique=False)
    op.create_index(op.f('ix_knowledge_ingestion_jobs_status'), 'knowledge_ingestion_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_ingestion_jobs_user_id'), 'knowledge_ingestion_jobs', ['user_id'], unique=False)
    op.create_table('library_assets',
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('library_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_library_assets_library_id'), 'library_assets', ['library_id'], unique=False)
    op.create_index(op.f('ix_library_assets_user_id'), 'library_assets', ['user_id'], unique=False)
    op.create_table('library_item_tags',
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('tag_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    op.create_table('library_items',
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('library_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('source_path', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('source_mime', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('source_size', sa.Integer(), nullable=False),
    sa.Column('source_mtime', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('cover_mode', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('cover_asset_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('index_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('graph_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_library_items_content_type'), 'library_items', ['content_type'], unique=False)
    op.create_index(op.f('ix_library_items_item_type'), 'library_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_library_items_library_id'), 'library_items', ['library_id'], unique=False)
    op.create_index(op.f('ix_library_items_parent_id'), 'library_items', ['parent_id'], unique=False)
    op.create_index(op.f('ix_library_items_sort_order'), 'library_items', ['sort_order'], unique=False)
    op.create_index(op.f('ix_library_items_source_path'), 'library_items', ['source_path'], unique=False)
    op.create_index(op.f('ix_library_items_storage_path'), 'library_items', ['storage_path'], unique=False)
    op.create_index(op.f('ix_library_items_user_id'), 'library_items', ['user_id'], unique=False)
    op.create_table('library_tags',
    sa.Column('tag_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('library_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index(op.f('ix_library_tags_library_id'), 'library_tags', ['library_id'], unique=False)
    op.create_index(op.f('ix_library_tags_name'), 'library_tags', ['name'], unique=False)
    op.create_index(op.f('ix_library_tags_user_id'), 'library_tags', ['user_id'], unique=False)
    op.create_table('literature_reading_states',
    sa.Column('state_id', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('library_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('form_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('row_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state_id'),
    sa.UniqueConstraint('user_id', 'library_id', 'form_id', 'row_id', name='uq_literature_reading_target')
    )
    op.create_index(op.f('ix_literature_reading_states_form_id'), 'literature_reading_states', ['form_id'], unique=False)
    op.create_index(op.f('ix_literature_reading_states_last_viewed_at'), 'literature_reading_states', ['last_viewed_at'], unique=False)
    op.create_index(op.f('ix_literature_reading_states_library_id'), 'literature_reading_states', ['library_id'], unique=False)
    op.create_index(op.f('ix_literature_reading_states_row_id'), 'literature_reading_states', ['row_id'], unique=False)
    op.create_index(op.f('ix_literature_reading_states_user_id'), 'literature_reading_states', ['user_id'], unique=False)
    op.create_table('longterm_memory_specs',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('memory_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source_uri', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('source_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('source_range_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('authority', sa.Float(), nullable=False),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('embedding_vector_json', sa.JSON(), nullable=True),
    sa.Column('memory_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index(op.f('ix_longterm_memory_specs_created_at'), 'longterm_memory_specs', ['created_at'], unique=False)
    op.create_index(op.f('ix_longterm_memory_specs_memory_type'), 'longterm_memory_specs', ['memory_type'], unique=False)
    op.create_index(op.f('ix_longterm_memory_specs_session_id'), 'longterm_memory_specs', ['session_id'], unique=False)
    op.create_index(op.f('ix_longterm_memory_specs_source_hash'), 'longterm_memory_specs', ['source_hash'], unique=False)
    op.create_index(op.f('ix_longterm_memory_specs_source_id'), 'longterm_memory_specs', ['source_id'], unique=False)
    op.create_index(op.f('ix_longterm_memory_specs_source_type'), 'longterm_memory_specs', ['source_type'], unique=False)
    op.create_index(op.f('ix_longterm_memory_specs_tag'), 'longterm_memory_specs', ['tag'], unique=False)
    op.create_index(op.f('ix_longterm_memory_specs_updated_at'), 'longterm_memory_specs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_longterm_memory_specs_user_id'), 'longterm_memory_specs', ['user_id'], unique=False)
    op.create_index(op.f('ix_longterm_memory_specs_valid_from'), 'longterm_memory_specs', ['valid_from'], unique=False)
    op.create_index(op.f('ix_longterm_memory_specs_valid_until'), 'longterm_memory_specs', ['valid_until'], unique=False)
    op.create_table('privacy_records',
    sa.Column('privacy_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('library_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('privacy_id'),
    sa.UniqueConstraint('user_id', 'library_id', 'target_type', 'target_id', name='uq_privacy_target')
    )
    op.create_index(op.f('ix_privacy_records_created_at'), 'privacy_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_privacy_records_library_id'), 'privacy_records', ['library_id'], unique=False)
    op.create_index(op.f('ix_privacy_records_target_id'), 'privacy_records', ['target_id'], unique=False)
    op.create_index(op.f('ix_privacy_records_target_type'), 'privacy_records', ['target_type'], unique=False)
    op.create_index(op.f('ix_privacy_records_user_id'), 'privacy_records', ['user_id'], unique=False)
    op.create_table('smart_form_cells',
    sa.Column('cell_record_id', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('form_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('row_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('column_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('asset_path', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.PrimaryKeyConstraint('cell_record_id'),
    sa.UniqueConstraint('form_id', 'row_id', 'column_id', name='uq_smart_form_cells_position')
    )
    op.create_index(op.f('ix_smart_form_cells_column_id'), 'smart_form_cells', ['column_id'], unique=False)
    op.create_index(op.f('ix_smart_form_cells_form_id'), 'smart_form_cells', ['form_id'], unique=False)
    op.create_index(op.f('ix_smart_form_cells_row_id'), 'smart_form_cells', ['row_id'], unique=False)
    op.create_table('smart_form_columns',
    sa.Column('column_record_id', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('form_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('column_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('column_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('removable', sa.Boolean(), nullable=False),
    sa.Column('editable', sa.Boolean(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.Column('tone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.PrimaryKeyConstraint('column_record_id'),
    sa.UniqueConstraint('form_id', 'column_id', name='uq_smart_form_columns_form_column')
    )
    op.create_index(op.f('ix_smart_form_columns_column_id'), 'smart_form_columns', ['column_id'], unique=False)
    op.create_index(op.f('ix_smart_form_columns_form_id'), 'smart_form_columns', ['form_id'], unique=False)
    op.create_index(op.f('ix_smart_form_columns_order_index'), 'smart_form_columns', ['order_index'], unique=False)
    op.create_table('smart_form_rows',
    sa.Column('row_record_id', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('form_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('row_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('row_record_id'),
    sa.UniqueConstraint('form_id', 'row_id', name='uq_smart_form_rows_form_row')
    )
    op.create_index(op.f('ix_smart_form_rows_created_at'), 'smart_form_rows', ['created_at'], unique=False)
    op.create_index(op.f('ix_smart_form_rows_form_id'), 'smart_form_rows', ['form_id'], unique=False)
    op.create_index(op.f('ix_smart_form_rows_order_index'), 'smart_form_rows', ['order_index'], unique=False)
    op.create_index(op.f('ix_smart_form_rows_row_id'), 'smart_form_rows', ['row_id'], unique=False)
    op.create_index(op.f('ix_smart_form_rows_updated_at'), 'smart_form_rows', ['updated_at'], unique=False)
    op.create_table('smart_forms',
    sa.Column('form_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('library_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('form_kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('asset_dir', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('form_id')
    )
    op.create_index(op.f('ix_smart_forms_form_kind'), 'smart_forms', ['form_kind'], unique=False)
    op.create_index(op.f('ix_smart_forms_library_id'), 'smart_forms', ['library_id'], unique=False)
    op.create_index(op.f('ix_smart_forms_title'), 'smart_forms', ['title'], unique=False)
    op.create_index(op.f('ix_smart_forms_updated_at'), 'smart_forms', ['updated_at'], unique=False)
    op.create_index(op.f('ix_smart_forms_user_id'), 'smart_forms', ['user_id'], unique=False)
    op.create_table('todo_imports',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('todos',
    sa.Column('todo_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_at', sa.DateTime(), nullable=True),
    sa.Column('recurrence_frequency', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('recurrence_interval', sa.Integer(), nullable=False),
    sa.Column('last_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('todo_id')
    )
    op.create_index(op.f('ix_todos_user_id'), 'todos', ['user_id'], unique=False)
    op.create_table('user_knowledge_libraries',
    sa.Column('library_id', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('knowledge_dir', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('library_storage_dir', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('library_id')
    )
    op.create_index(op.f('ix_user_knowledge_libraries_is_active'), 'user_knowledge_libraries', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_knowledge_libraries_knowledge_dir'), 'user_knowledge_libraries', ['knowledge_dir'], unique=False)
    op.create_index(op.f('ix_user_knowledge_libraries_user_id'), 'user_knowledge_libraries', ['user_id'], unique=False)
    op.create_table('user_llm_config',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('small_api_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('small_base_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('small_model_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_llm_config_presets',
    sa.Column('config_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index(op.f('ix_user_llm_config_presets_user_id'), 'user_llm_config_presets', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('knowledge_dir', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('proxy_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('browser_proxy_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('browser_home_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('web_search_enabled', sa.Boolean(), nullable=False),
    sa.Column('web_search_max_results', sa.Integer(), nullable=False),
    sa.Column('auto_ingest_on_upload', sa.Boolean(), nullable=False),
    sa.Column('ocr_enabled', sa.Boolean(), nullable=False),
    sa.Column('long_term_memory_enabled', sa.Boolean(), nullable=False),
    sa.Column('knowledge_ignore_patterns', sa.Text(), nullable=True),
    sa.Column('disabled_tools', sa.Text(), nullable=True),
    sa.Column('terminal_sandbox_config', sa.Text(), nullable=True),
    sa.Column('ui_font_families', sa.Text(), nullable=True),
    sa.Column('text_font_families', sa.Text(), nullable=True),
    sa.Column('ui_font_size_percent', sa.Integer(), nullable=False),
    sa.Column('text_font_size_percent', sa.Integer(), nullable=False),
    sa.Column('font_size_percent', sa.Integer(), nullable=False),
    sa.Column('theme_primary_color', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('theme_soft_color', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('background_cover_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('show_backlinks', sa.Boolean(), nullable=False),
    sa.Column('graph_node_limit', sa.Integer(), nullable=False),
    sa.Column('floating_launch_enabled', sa.Boolean(), nullable=False),
    sa.Column('editor_image_assets_dir', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('storage_path_overrides', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_system_prompts',
    sa.Column('prompt_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    op.create_index(op.f('ix_user_system_prompts_user_id'), 'user_system_prompts', ['user_id'], unique=False)
    op.create_table('vault_assets',
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_vault_assets_item_id'), 'vault_assets', ['item_id'], unique=False)
    op.create_index(op.f('ix_vault_assets_user_id'), 'vault_assets', ['user_id'], unique=False)
    op.create_table('vault_item_tags',
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('tag_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    op.create_table('vault_items',
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_vault_items_deleted_at'), 'vault_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_vault_items_item_type'), 'vault_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_vault_items_user_id'), 'vault_items', ['user_id'], unique=False)
    op.create_table('vault_profiles',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('password_salt', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('debug_master_password', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('kdf_iterations', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('vault_tags',
    sa.Column('tag_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index(op.f('ix_vault_tags_name'), 'vault_tags', ['name'], unique=False)
    op.create_index(op.f('ix_vault_tags_user_id'), 'vault_tags', ['user_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_call_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('tool_calls_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_summarized', sa.Boolean(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_agent_messages_created_at'), 'agent_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_messages_is_summarized'), 'agent_messages', ['is_summarized'], unique=False)
    op.create_index(op.f('ix_agent_messages_role'), 'agent_messages', ['role'], unique=False)
    op.create_index(op.f('ix_agent_messages_session_id'), 'agent_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_tool_call_id'), 'agent_messages', ['tool_call_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_user_id'), 'agent_messages', ['user_id'], unique=False)
    op.create_table('session_attachments',
    sa.Column('attachment_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('library_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('library_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('stored_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('text_path', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_index(op.f('ix_session_attachments_created_at'), 'session_attachments', ['created_at'], unique=False)
    op.create_index(op.f('ix_session_attachments_library_id'), 'session_attachments', ['library_id'], unique=False)
    op.create_index(op.f('ix_session_attachments_session_id'), 'session_attachments', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_attachments_user_id'), 'session_attachments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_attachments_user_id'), table_name='session_attachments')
    op.drop_index(op.f('ix_session_attachments_session_id'), table_name='session_attachments')
    op.drop_index(op.f('ix_session_attachments_library_id'), table_name='session_attachments')
    op.drop_index(op.f('ix_session_attachments_created_at'), table_name='session_attachments')
    op.drop_table('session_attachments')
    op.drop_index(op.f('ix_agent_messages_user_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_tool_call_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_session_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_role'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_is_summarized'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_created_at'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_vault_tags_user_id'), table_name='vault_tags')
    op.drop_index(op.f('ix_vault_tags_name'), table_name='vault_tags')
    op.drop_table('vault_tags')
    op.drop_table('vault_profiles')
    op.drop_index(op.f('ix_vault_items_user_id'), table_name='vault_items')
    op.drop_index(op.f('ix_vault_items_item_type'), table_name='vault_items')
    op.drop_index(op.f('ix_vault_items_deleted_at'), table_name='vault_items')
    op.drop_table('vault_items')
    op.drop_table('vault_item_tags')
    op.drop_index(op.f('ix_vault_assets_user_id'), table_name='vault_assets')
    op.drop_index(op.f('ix_vault_assets_item_id'), table_name='vault_assets')
    op.drop_table('vault_assets')
    op.drop_index(op.f('ix_user_system_prompts_user_id'), table_name='user_system_prompts')
    op.drop_table('user_system_prompts')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_llm_config_presets_user_id'), table_name='user_llm_config_presets')
    op.drop_table('user_llm_config_presets')
    op.drop_table('user_llm_config')
    op.drop_index(op.f('ix_user_knowledge_libraries_user_id'), table_name='user_knowledge_libraries')
    op.drop_index(op.f('ix_user_knowledge_libraries_knowledge_dir'), table_name='user_knowledge_libraries')
    op.drop_index(op.f('ix_user_knowledge_libraries_is_active'), table_name='user_knowledge_libraries')
    op.drop_table('user_knowledge_libraries')
    op.drop_index(op.f('ix_todos_user_id'), table_name='todos')
    op.drop_table('todos')
    op.drop_table('todo_imports')
    op.drop_index(op.f('ix_smart_forms_user_id'), table_name='smart_forms')
    op.drop_index(op.f('ix_smart_forms_updated_at'), table_name='smart_forms')
    op.drop_index(op.f('ix_smart_forms_title'), table_name='smart_forms')
    op.drop_index(op.f('ix_smart_forms_library_id'), table_name='smart_forms')
    op.drop_index(op.f('ix_smart_forms_form_kind'), table_name='smart_forms')
    op.drop_table('smart_forms')
    op.drop_index(op.f('ix_smart_form_rows_updated_at'), table_name='smart_form_rows')
    op.drop_index(op.f('ix_smart_form_rows_row_id'), table_name='smart_form_rows')
    op.drop_index(op.f('ix_smart_form_rows_order_index'), table_name='smart_form_rows')
    op.drop_index(op.f('ix_smart_form_rows_form_id'), table_name='smart_form_rows')
    op.drop_index(op.f('ix_smart_form_rows_created_at'), table_name='smart_form_rows')
    op.drop_table('smart_form_rows')
    op.drop_index(op.f('ix_smart_form_columns_order_index'), table_name='smart_form_columns')
    op.drop_index(op.f('ix_smart_form_columns_form_id'), table_name='smart_form_columns')
    op.drop_index(op.f('ix_smart_form_columns_column_id'), table_name='smart_form_columns')
    op.drop_table('smart_form_columns')
    op.drop_index(op.f('ix_smart_form_cells_row_id'), table_name='smart_form_cells')
    op.drop_index(op.f('ix_smart_form_cells_form_id'), table_name='smart_form_cells')
    op.drop_index(op.f('ix_smart_form_cells_column_id'), table_name='smart_form_cells')
    op.drop_table('smart_form_cells')
    op.drop_index(op.f('ix_privacy_records_user_id'), table_name='privacy_records')
    op.drop_index(op.f('ix_privacy_records_target_type'), table_name='privacy_records')
    op.drop_index(op.f('ix_privacy_records_target_id'), table_name='privacy_records')
    op.drop_index(op.f('ix_privacy_records_library_id'), table_name='privacy_records')
    op.drop_index(op.f('ix_privacy_records_created_at'), table_name='privacy_records')
    op.drop_table('privacy_records')
    op.drop_index(op.f('ix_longterm_memory_specs_valid_until'), table_name='longterm_memory_specs')
    op.drop_index(op.f('ix_longterm_memory_specs_valid_from'), table_name='longterm_memory_specs')
    op.drop_index(op.f('ix_longterm_memory_specs_user_id'), table_name='longterm_memory_specs')
    op.drop_index(op.f('ix_longterm_memory_specs_updated_at'), table_name='longterm_memory_specs')
    op.drop_index(op.f('ix_longterm_memory_specs_tag'), table_name='longterm_memory_specs')
    op.drop_index(op.f('ix_longterm_memory_specs_source_type'), table_name='longterm_memory_specs')
    op.drop_index(op.f('ix_longterm_memory_specs_source_id'), table_name='longterm_memory_specs')
    op.drop_index(op.f('ix_longterm_memory_specs_source_hash'), table_name='longterm_memory_specs')
    op.drop_index(op.f('ix_longterm_memory_specs_session_id'), table_name='longterm_memory_specs')
    op.drop_index(op.f('ix_longterm_memory_specs_memory_type'), table_name='longterm_memory_specs')
    op.drop_index(op.f('ix_longterm_memory_specs_created_at'), table_name='longterm_memory_specs')
    op.drop_table('longterm_memory_specs')
    op.drop_index(op.f('ix_literature_reading_states_user_id'), table_name='literature_reading_states')
    op.drop_index(op.f('ix_literature_reading_states_row_id'), table_name='literature_reading_states')
    op.drop_index(op.f('ix_literature_reading_states_library_id'), table_name='literature_reading_states')
    op.drop_index(op.f('ix_literature_reading_states_last_viewed_at'), table_name='literature_reading_states')
    op.drop_index(op.f('ix_literature_reading_states_form_id'), table_name='literature_reading_states')
    op.drop_table('literature_reading_states')
    op.drop_index(op.f('ix_library_tags_user_id'), table_name='library_tags')
    op.drop_index(op.f('ix_library_tags_name'), table_name='library_tags')
    op.drop_index(op.f('ix_library_tags_library_id'), table_name='library_tags')
    op.drop_table('library_tags')
    op.drop_index(op.f('ix_library_items_user_id'), table_name='library_items')
    op.drop_index(op.f('ix_library_items_storage_path'), table_name='library_items')
    op.drop_index(op.f('ix_library_items_source_path'), table_name='library_items')
    op.drop_index(op.f('ix_library_items_sort_order'), table_name='library_items')
    op.drop_index(op.f('ix_library_items_parent_id'), table_name='library_items')
    op.drop_index(op.f('ix_library_items_library_id'), table_name='library_items')
    op.drop_index(op.f('ix_library_items_item_type'), table_name='library_items')
    op.drop_index(op.f('ix_library_items_content_type'), table_name='library_items')
    op.drop_table('library_items')
    op.drop_table('library_item_tags')
    op.drop_index(op.f('ix_library_assets_user_id'), table_name='library_assets')
    op.drop_index(op.f('ix_library_assets_library_id'), table_name='library_assets')
    op.drop_table('library_assets')
    op.drop_index(op.f('ix_knowledge_ingestion_jobs_user_id'), table_name='knowledge_ingestion_jobs')
    op.drop_index(op.f('ix_knowledge_ingestion_jobs_status'), table_name='knowledge_ingestion_jobs')
    op.drop_index(op.f('ix_knowledge_ingestion_jobs_path'), table_name='knowledge_ingestion_jobs')
    op.drop_index(op.f('ix_knowledge_ingestion_jobs_library_id'), table_name='knowledge_ingestion_jobs')
    op.drop_index(op.f('ix_knowledge_ingestion_jobs_created_at'), table_name='knowledge_ingestion_jobs')
    op.drop_index(op.f('ix_knowledge_ingestion_jobs_cancel_requested'), table_name='knowledge_ingestion_jobs')
    op.drop_table('knowledge_ingestion_jobs')
    op.drop_index(op.f('ix_knowledge_graph_nodes_user_id'), table_name='knowledge_graph_nodes')
    op.drop_index(op.f('ix_knowledge_graph_nodes_updated_at'), table_name='knowledge_graph_nodes')
    op.drop_index(op.f('ix_knowledge_graph_nodes_normalized_label'), table_name='knowledge_graph_nodes')
    op.drop_index(op.f('ix_knowledge_graph_nodes_node_type'), table_name='knowledge_graph_nodes')
    op.drop_index(op.f('ix_knowledge_graph_nodes_library_id'), table_name='knowledge_graph_nodes')
    op.drop_index(op.f('ix_knowledge_graph_nodes_label'), table_name='knowledge_graph_nodes')
    op.drop_index(op.f('ix_knowledge_graph_nodes_entity_type'), table_name='knowledge_graph_nodes')
    op.drop_index(op.f('ix_knowledge_graph_nodes_document_id'), table_name='knowledge_graph_nodes')
    op.drop_index(op.f('ix_knowledge_graph_nodes_created_at'), table_name='knowledge_graph_nodes')
    op.drop_table('knowledge_graph_nodes')
    op.drop_index(op.f('ix_knowledge_graph_edges_user_id'), table_name='knowledge_graph_edges')
    op.drop_index(op.f('ix_knowledge_graph_edges_updated_at'), table_name='knowledge_graph_edges')
    op.drop_index(op.f('ix_knowledge_graph_edges_target_node_id'), table_name='knowledge_graph_edges')
    op.drop_index(op.f('ix_knowledge_graph_edges_source_section_id'), table_name='knowledge_graph_edges')
    op.drop_index(op.f('ix_knowledge_graph_edges_source_node_id'), table_name='knowledge_graph_edges')
    op.drop_index(op.f('ix_knowledge_graph_edges_source_document_id'), table_name='knowledge_graph_edges')
    op.drop_index(op.f('ix_knowledge_graph_edges_relation_type'), table_name='knowledge_graph_edges')
    op.drop_index(op.f('ix_knowledge_graph_edges_library_id'), table_name='knowledge_graph_edges')
    op.drop_index(op.f('ix_knowledge_graph_edges_created_at'), table_name='knowledge_graph_edges')
    op.drop_table('knowledge_graph_edges')
    op.drop_index(op.f('ix_knowledge_graph_document_status_user_id'), table_name='knowledge_graph_document_status')
    op.drop_index(op.f('ix_knowledge_graph_document_status_updated_at'), table_name='knowledge_graph_document_status')
    op.drop_index(op.f('ix_knowledge_graph_document_status_status'), table_name='knowledge_graph_document_status')
    op.drop_index(op.f('ix_knowledge_graph_document_status_source_hash'), table_name='knowledge_graph_document_status')
    op.drop_index(op.f('ix_knowledge_graph_document_status_library_id'), table_name='knowledge_graph_document_status')
    op.drop_index(op.f('ix_knowledge_graph_document_status_document_id'), table_name='knowledge_graph_document_status')
    op.drop_table('knowledge_graph_document_status')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_target_type'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_target_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_library_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_created_at'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_automation_tasks_user_id'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_todo_id'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_next_run_at'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_lease_until'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_lease_id'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_enabled'), table_name='automation_tasks')
    op.drop_table('automation_tasks')
    op.drop_index(op.f('ix_automation_runs_user_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_automation_id'), table_name='automation_runs')
    op.drop_table('automation_runs')
    op.drop_index(op.f('ix_agent_token_usage_user_id'), table_name='agent_token_usage')
    op.drop_index(op.f('ix_agent_token_usage_total_tokens'), table_name='agent_token_usage')
    op.drop_index(op.f('ix_agent_token_usage_session_id'), table_name='agent_token_usage')
    op.drop_index(op.f('ix_agent_token_usage_node'), table_name='agent_token_usage')
    op.drop_index(op.f('ix_agent_token_usage_model_tier'), table_name='agent_token_usage')
    op.drop_index(op.f('ix_agent_token_usage_model_name'), table_name='agent_token_usage')
    op.drop_index(op.f('ix_agent_token_usage_message_id'), table_name='agent_token_usage')
    op.drop_index(op.f('ix_agent_token_usage_created_at'), table_name='agent_token_usage')
    op.drop_table('agent_token_usage')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_updated_at'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_created_at'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_agent_queue_tasks_user_id'), table_name='agent_queue_tasks')
    op.drop_index(op.f('ix_agent_queue_tasks_updated_at'), table_name='agent_queue_tasks')
    op.drop_index(op.f('ix_agent_queue_tasks_status'), table_name='agent_queue_tasks')
    op.drop_index(op.f('ix_agent_queue_tasks_session_id'), table_name='agent_queue_tasks')
    op.drop_index(op.f('ix_agent_queue_tasks_priority'), table_name='agent_queue_tasks')
    op.drop_index(op.f('ix_agent_queue_tasks_previous_task_id'), table_name='agent_queue_tasks')
    op.drop_index(op.f('ix_agent_queue_tasks_created_at'), table_name='agent_queue_tasks')
    op.drop_table('agent_queue_tasks')
    op.drop_table('agent_queue_settings')
    op.drop_index(op.f('ix_agent_change_snapshots_user_id'), table_name='agent_change_snapshots')
    op.drop_index(op.f('ix_agent_change_snapshots_session_id'), table_name='agent_change_snapshots')
    op.drop_index(op.f('ix_agent_change_snapshots_run_id'), table_name='agent_change_snapshots')
    op.drop_index(op.f('ix_agent_change_snapshots_is_undone'), table_name='agent_change_snapshots')
    op.drop_index(op.f('ix_agent_change_snapshots_is_finalized'), table_name='agent_change_snapshots')
    op.drop_index(op.f('ix_agent_change_snapshots_created_at'), table_name='agent_change_snapshots')
    op.drop_table('agent_change_snapshots')
    op.drop_index(op.f('ix_activity_events_user_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_source'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_object_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_module'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_created_at'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_action'), table_name='activity_events')
    op.drop_table('activity_events')
    # ### end Alembic commands ###
